[workspace]
channels = ["knime/label/nightly", "knime", "conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]
test = { cmd = "pytest" }

[dependencies]
python = "3.11.*"
knime-extension = "5.7.*"
knime-python-base = "5.7.*"
knime-python-scripting = "5.7.*"
knime-python-versions = "5.7.*"
rdkit = "*"
pytest = "*"
ipykernel = "*"

[feature.build.dependencies]
python = "3.9.*"
knime-extension-bundling = "5.7.*"

[feature.debug.dependencies]
debugpy = "*"

[feature.build.tasks]
build = { args = [{ "arg" = "dest", "default" = "./local-update-site" }], cmd = "build-python-extension . {{ dest }}"}

[environments]
build = {features = ["build"], no-default-feature = true}
debug = {features = ["debug"]}
